### ISSUE TITLE
Кажется надо добавить обработку этих ошибок

### ISSUE THREAD

**Issue by trkohler** [fk-war-in-ukraine/report-telegram-channels#4]
```
    resp = conn.urlopen(
  File "/home/troyalekson/my/NoWarDDoS/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/troyalekson/my/NoWarDDoS/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/troyalekson/my/NoWarDDoS/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/troyalekson/my/NoWarDDoS/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/troyalekson/my/NoWarDDoS/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/troyalekson/my/NoWarDDoS/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))


During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "attack.py", line 192, in <module>
    status, site = task.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "attack.py", line 113, in mainth
    content = scraper.get(host).content
  File "/home/troyalekson/my/NoWarDDoS/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/home/troyalekson/my/NoWarDDoS/venv/lib/python3.8/site-packages/cloudscraper/__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "/home/troyalekson/my/NoWarDDoS/venv/lib/python3.8/site-packages/cloudscraper/__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "/home/troyalekson/my/NoWarDDoS/venv/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/troyalekson/my/NoWarDDoS/venv/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/troyalekson/my/NoWarDDoS/venv/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by trkohler** [comment]
не в тот репозиторий
